---
title: "PA1_template.Rmd"
author: "Venkata Cherkadu Vasala"
date: "Tuesday, November 11, 2014"
output: html_document
---

Loading and Pre-Processing Data
-------------------------------

1.    Load the data (i.e. read.csv())

    ``` {r, echo = TRUE}
    # set the working directory 
    setwd("~/Data/Venkata/Personal/Coursera/reproducible_research/Working_Directory")
    
    # read the downloaded csv file from the data directory 
    activity.df <- read.csv("Data//activity.csv") ## requires Data directory 
    ##to be present in working 
    ```
2.    PreProcessing of the Data

    ``` {r, echo = TRUE}
    # aggregate the activity data for each day
    activity.day.df  <- aggregate(activity.df$steps, 
                         by        = list(activity.df$date),
                         FUN       = "sum",
                         na.rm     = TRUE)
    
    #change the names of the columns of the data frame for plotting ease
    names(activity.day.df) <- c("Date", "TotalStepsPerDay")
    
    # average number of steps for all days per each interval using aggregate
    # function
    activity.interval.df <- aggregate(activity.df$steps, 
                         by        = list(activity.df$interval),
                         FUN       = "mean",
                         na.rm     = TRUE)
    names(activity.interval.df) <- c("interval", "AverageSteps" )
    ```






